name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Update Composer
        run: composer self-update
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: "${{ secrets.DB_HOST }}"
          DB_DATABASE: "${{ secrets.DB_NAME }}"
          DB_USERNAME: "${{ secrets.DB_USERNAME }}"
          DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
          DB_PORT: "${{ secrets.DB_PORT }}"
        run: php artisan migrate --pretend
      - name: Remove .env file
        run: rm -f .env
      - name: Upload backend
        # You may pin to the exact commit or the version.
        # uses: sebastianpopp/git-ftp-action@33a94c0e0fce59ca477baa9d1748a5f2e53fb429
        uses: sebastianpopp/git-ftp-action@3.0.0
        with:
          # URL
          url: "ftp://${{ secrets.FTP_HOST }}"
          # FTP login name
          user: "${{ secrets.FTP_USERNAME }}"
          # FTP password
          password: "${{ secrets.FTP_PASSWORD }}"
