name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Update Composer
        run: composer self-update
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: "${{ secrets.DB_HOST }}"
          DB_DATABASE: "${{ secrets.DB_NAME }}"
          DB_USERNAME: "${{ secrets.DB_USERNAME }}"
          DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
          DB_PORT: "${{ secrets.DB_PORT }}"
        run: php artisan migrate --pretend
      - uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          # ftp server
          server: "${{ secrets.FTP_HOST }}"
          # ftp username
          username: "${{ secrets.FTP_USERNAME }}"
          # ftp password
          password: "${{ secrets.FTP_PASSWORD }}"
          # Server port to connect to (read your web hosts docs)
          port: 21
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: ftp # optional
          # Folder to upload from, must end with trailing slash /
          #         local-dir: # optional
          # Path to upload to on the server. Must end with trailing slash /
          #         server-dir: # optional
          # Path and name of the state file - this file is used to track which files have been deployed
          state-name: upload_state.json # optional
          # Prints which modifications will be made with current config options, but doesnt actually make any changes
          #         dry-run: # optional
          # Deletes ALL contents of server-dir, even items in excluded with exclude argument
          #         dangerous-clean-slate: # optional
          # An array of glob patterns, these files will not be included in the publish/delete process
#          exclude: |
#            .git*
#            **/.git*
#            **/node_modules/**
#            bootstrap/cache/**
#            database/migrations/**
#            tests
          # How verbose should the information be - minimal, standard, or verbose
          log-level: minimal # optional
          # strict or loose
          security: strict # optional
